### ISSUE TITLE
Dataset is not available 

### ISSUE THREAD

**Issue by zhongguadepi** [joellliu/SegmentAndComplete#11]
您好，APRICOT-Mask dataset 数据集无法下载，然后Train the patch segmenter  数据集格式是？该如何用自己的数据集训练patch segmenter

**Comment by joellliu** [comment]
数据集是连接不上吗？数据集格式参考代码里的定义 
https://github.com/joellliu/SegmentAndComplete/blob/main/generate_adv_data_coco.py

**Comment by zhongguadepi** [comment]
是的，APRICOT-Mask dataset 数据集无法下载。能否提供百度网盘链接等方式

**Comment by joellliu** [comment]
试试onedrive
https://livejohnshopkins-my.sharepoint.com/:f:/g/personal/jliu214_jh_edu/EnZTQY21vGRMsrRY03cD9HYBYlYSgzT-7wzAAkMo6LiozA?e=2x4ErW
