### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by LeeWlving** [joellliu/SegmentAndComplete#4]
Thank you for your great job. When I run your code, an error occured!
 File "train_coco.py", line 12, in <module>
from eval import eval_net
ModuleNotFoundError: No module named 'eval'
Do you know the possible reason to solve this?

**Comment by joellliu** [comment]
Hi, the evaluation code has been uploaded.
https://github.com/joellliu/SegmentAndComplete/blob/main/eval.py
