### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by hacktfj** [joellliu/SegmentAndComplete#5]
尊敬的作者您好，请问该报错该如何处理？希望大佬在百忙之中，指点迷津。
 python generate_adv_data_coco.py --random 

File "generate_adv_data_coco.py", line 41, in <module>
    art_model = PyTorchFasterRCNN(
TypeError: Can't instantiate abstract class PyTorchFasterRCNN with abstract methods native_label_is_pytorch_format

**Comment by joellliu** [comment]
您好！这应该是torchvision版本问题引起的，可以考虑安装torch==1.8.1，torchvision==0.9.1

**Comment by hacktfj** [comment]
谢谢大哥

**Comment by fatgog** [comment]
> 您好！这应该是torchvision版本问题引起的，可以考虑安装torch==1.8.1，torchvision==0.9.1

作者您好，我也出现这个问题，torch+torchvision也按照您说的版本安装，但是问题仍未解决
