### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by XinDong10** [joellliu/SegmentAndComplete#6]
作者大佬，可以问下您提供的已处理的数据是使用PGDpatch的patch对抗攻击方法生成的嘛？这个方法是之前有文章提出的嘛？ 为什么下载之后是pth文件呢？如果想直接得到图像的话，可以请作者大佬说说是哪段解析代码嘛。

**Comment by joellliu** [comment]
下载数据里面包含了原始图像和label，以及patch的位置，没有被攻击后生成的图像。PGDPatch是pgd在patch attack上的简单拓展，应该没有专门的文章。pth文件是为了方便保存和读取，可以参考这段代码：
https://github.com/joellliu/SegmentAndComplete/blob/db1286214d615d80be39f537b627db0b3e3b81d8/eval_object_detection_coco.py#L212C37-L212C37
