### ISSUE TITLE
Dataset is not available :( 

### ISSUE THREAD

**Issue by TigDang** [joellliu/SegmentAndComplete#9]
Thank you guys for that great work! But I have a problem with downloading Artifact-mask dataset due server is not responses. Did you have any other sources?

**Comment by joellliu** [comment]
Hi the server seems to be working. Can you try again?

**Comment by joellliu** [comment]
@TigDang I uploaded the dataset to OneDrive in case you are still having trouble downloading it
https://livejohnshopkins-my.sharepoint.com/:f:/g/personal/jliu214_jh_edu/EnZTQY21vGRMsrRY03cD9HYBYlYSgzT-7wzAAkMo6LiozA?e=2x4ErW
